CREATE TABLE COLOUR(
	COLOUR_ID INT PRIMARY KEY,
	NAME VARCHAR(15),
	EXTRA_FEE INT
);

CREATE TABLE CUSTOMER1(
	ID INT PRIMARY KEY,
	FAVORITE_COLOUR_ID INT,
	FOREIGN KEY (FAVORITE_COLOUR_ID) REFERENCES COLOUR(COLOUR_ID),
	FIRST_NAME VARCHAR(15),
	LAST_NAME VARCHAR(15)
);

CREATE TABLE CATEGORY(
	ID INT PRIMARY KEY,
	NAME VARCHAR(15),
	PARENT_ID INT
);

CREATE TABLE CLOTHING(
	ID INT PRIMARY KEY,
	NAME VARCHAR(15),
	SIZE VARCHAR(15),
	PRICE DECIMAL(8,2),
	COLOUR_ID INT
	FOREIGN KEY (COLOUR_ID) REFERENCES COLOUR(COLOUR_ID),
	CATEGORY_ID INT
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE CLOTHING_ORDER(
	ID INT PRIMARY KEY,
	CUSTOMER_ID INT,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER1(ID),
	CLOTHING_ID INT,
	FOREIGN KEY (CLOTHING_ID) REFERENCES CLOTHING(ID),
	ITEMS INT,
	ORDER_DATE DATETIME
);

--1
SELECT CUSTOMER1.FIRST_NAME
FROM CUSTOMER1 INNER JOIN COLOUR
ON COLOUR.COLOUR_ID = CUSTOMER1.FAVORITE_COLOUR_ID
WHERE COLOUR.NAME IN ('RED' , 'GREEN') 
AND
CUSTOMER1.FIRST_NAME IN ('JAY' , 'DHRUV');

--2
SELECT CLOTHING.NAME , CLOTHING.SIZE
FROM CLOTHING INNER JOIN CATEGORY
ON CLOTHING.CATEGORY_ID = CATEGORY.ID
WHERE CATEGORY.NAME = 'JOGGERS';

--3
SELECT CLOTHING_ORDER.ITEMS
FROM CUSTOMER1 
INNER JOIN CLOTHING_ORDER ON CUSTOMER1.ID = CLOTHING_ORDER.CUSTOMER_ID
INNER JOIN CLOTHING ON CLOTHING_ORDER.CLOTHING_ID = CLOTHING.ID
INNER JOIN CATEGORY ON CATEGORY.ID = CLOTHING.CATEGORY_ID 
WHERE CUSTOMER1.FIRST_NAME = 'JAY' 
AND CATEGORY.NAME = 'T-SHIRT'
AND CLOTHING_ORDER.ORDER_DATE > '2024-04-01';

--4
SELECT CUSTOMER1.FIRST_NAME
FROM CUSTOMER1 INNER JOIN COLOUR
ON CUSTOMER1.FAVORITE_COLOUR_ID = COLOUR.COLOUR_ID
WHERE COLOUR.EXTRA_FEE IS NOT NULL;

--5
SELECT MAX(CLOTHING.PRICE) , MIN(CLOTHING.PRICE) , AVG(CLOTHING.PRICE)
, CLOTHING_ORDER.ITEMS
FROM CLOTHING INNER JOIN CLOTHING_ORDER
ON CLOTHING.ID = CLOTHING_ORDER.CLOTHING_ID
INNER JOIN CATEGORY
ON CLOTHING.CATEGORY_ID = CATEGORY.ID
GROUP BY CATEGORY.ID;

--6
SELECT CUSTOMER1.FIRST_NAME 
FROM CUSTOMER1 INNER JOIN CLOTHING_ORDER
ON CUSTOMER1.ID = CLOTHING_ORDER.CUSTOMER_ID
WHERE CLOTHING_ORDER.ITEMS = 0;

--7
