CREATE TABLE CRICKET(
	NAME VARCHAR(50),
	CITY VARCHAR(50),
	AGE INT
);
SELECT * FROM CRICKET;

INSERT INTO CRICKET VALUES ('SACHIN TENDULKAR','MUMBAI',30);
INSERT INTO CRICKET VALUES ('RAHUL DRAVID','BOMBAY',30);
INSERT INTO CRICKET VALUES ('M.S.DHONI','JHARKHAND',30);
INSERT INTO CRICKET VALUES ('SURESH RAINA','GUJRAT',30);

--1.Create table Worldcup from cricket with all the columns and data.
SELECT * INTO WORLDCUP FROM CRICKET;
SELECT * FROM WORLDCUP;
--2.Create table T20 from cricket with first two columns with no data.
SELECT NAME,CITY INTO T20 FROM CRICKET WHERE 0=2;
SELECT * FROM T20;
--3.Create table IPL From Cricket with No Data
SELECT * INTO IPL FROM CRICKET WHERE 2=20;
SELECT * FROM IPL;

--Update Operation
--Part – A:
--From the above given tables perform the following queries (UPDATE Operation):

--1.Update deposit amount of all customers from 3000 to 5000. (Use Deposit Table)
UPDATE DEPOSIT SET AMOUNT = 5000 WHERE AMOUNT = 3000;
SELECT * FROM DEPOSIT;

--2.Change branch name of ANIL from VRCE to C.G. ROAD. (Use Borrow Table)
UPDATE BORROW SET BNAME = 'C.G.ROAD' WHERE BNAME = 'VRCE';
SELECT * FROM BORROW;

--3.Update Account No of SANDIP to 111 & Amount to 5000. (Use Deposit Table)
UPDATE DEPOSIT SET ACTNO=111,AMOUNT=5000 WHERE CNAME='SANDIP';
SELECT * FROM DEPOSIT;

--4.Update amount of KRANTI to 7000. (Use Deposit Table)
UPDATE DEPOSIT SET AMOUNT=7000 WHERE CNAME='KRANTI';
SELECT * FROM DEPOSIT;

--5.Update branch name from ANDHERI to ANDHERI WEST. (Use Branch Table)
UPDATE BRANCH SET BNAME = 'ANDHERI WEST' WHERE BNAME='ANDHERI';
SELECT * FROM BRANCH;

--6.Update branch name of MEHUL to NEHRU PALACE. (Use Deposit Table)
UPDATE DEPOSIT SET CNAME='NEHRU PLACE' WHERE CNAME='MEHUL';
SELECT * FROM DEPOSIT;

--7.Update deposit amount of all depositors to 5000 whose account no between 103 & 107. (Use Deposit Table)
UPDATE DEPOSIT SET AMOUNT=5000 WHERE ACTNO BETWEEN 103 AND 107
SELECT * FROM DEPOSIT;

--8. Update ADATE of ANIL to 1-4-95. (Use Deposit Table)
UPDATE DEPOSIT SET ADATE='1995-04-01' WHERE CNAME='ANIL';
SELECT * FROM DEPOSIT;

--9.Update the amount of MINU to 10000. (Use Deposit Table)
UPDATE DEPOSIT SET AMOUNT=10000 WHERE CNAME='MINU';
SELECT * FROM DEPOSIT;

--10.Update deposit amount of PRAMOD to 5000 and ADATE to 1-4-96 (Use Deposit Table)
UPDATE DEPOSIT SET AMOUNT=5000,ADATE='1996-04-01' WHERE CNAME='PRAMOD';
SELECT * FROM DEPOSIT;



--PART B
